"""Color-LCD UI for the StickS3 Narrator.

No touch, no buttons. Shows the current label centered on screen, sized by
_LAYOUT_TABLE and colored per phrases.py's color_for_tag().

Landscape (240x135), not the panel's native portrait orientation. ROTATION
is 1 or 3 depending on which physical edge should be "up" -- not confirmed
against hardware.

_LAYOUT_TABLE is generated by assets/_simulate_text_fit.py (not present in
this checkout): for each label, the largest DejaVu bitmap size
(9/12/18/24/40/56/72) that fits within a 10% margin, splitting two/three
word labels across two lines where that allows a larger font. A label not
in the table falls back to _fallback_layout's single-line estimate.

Text is positioned with plain setCursor(x, y) + print(line), not
setTextDatum()/drawString() -- the latter raised on hardware in an earlier
version. x is computed from _LAYOUT_TABLE's pixel widths; y stacks lines
from a vertically centered block.
"""

import M5
from M5 import *

from phrases import color_for_tag, label_for_tag

WHITE = 0xFFFFFF
BLACK = 0x000000
BLUE = 0x2060FF
AMBER = 0xFFA000  # boot screen only

# Native panel is 135x240 (portrait); rotated 90 degrees these swap. If
# text renders upside-down or mirrored, change to 3.
ROTATION = 1
SCREEN_W = 240
SCREEN_H = 135

MARGIN = 10
LINE_GAP = 4
_DEJAVU_NAMES = {
    9: "DejaVu9", 12: "DejaVu12", 18: "DejaVu18", 24: "DejaVu24",
    40: "DejaVu40", 56: "DejaVu56", 72: "DejaVu72",
}
# Largest first -- _fallback_layout tries each until one fits.
_FONT_CANDIDATES = (72, 56, 40, 24, 18, 12, 9)
# Average glyph width as a fraction of point size, for _fallback_layout only.
_CHAR_WIDTH_FACTOR = 0.62

# Keys are exact label text (phrases.py's label_for_tag). Values are
# (font_size, ((line1, pixel_width), ...)), one or two lines.
_LAYOUT_TABLE = {
    'Narrator ready': (40, (('Narrator', 169), ('ready', 115))),
    'Stopped': (40, (('Stopped', 165),)),
    'Color Quest': (40, (('Color', 104), ('Quest', 118))),
    'Freeze Dance': (40, (('Freeze', 135), ('Dance', 128))),
    'Jump In': (40, (('Jump In', 154),)),
    'Cooking': (40, (('Cooking', 160),)),
    'Melody': (40, (('Melody', 144),)),
    'Shake Fill': (40, (('Shake Fill', 192),)),
    'Shake Rainbow': (40, (('Shake', 123), ('Rainbow', 171))),
    'Rainbow': (40, (('Rainbow', 171),)),
    'Jump Counter': (40, (('Jump', 104), ('Counter', 160))),
    'Bell Choir': (40, (('Bell Choir', 192),)),
    'NFC Bell Choir': (40, (('NFC', 81), ('Bell Choir', 192))),
    'Ice Cream': (40, (('Ice', 59), ('Cream', 133))),
    'Multi Ice Cream': (40, (('Multi Ice', 170), ('Cream', 133))),
    'Gestures': (40, (('Gestures', 180),)),
    'Go': (72, (('Go', 100),)),
    'Freeze': (56, (('Freeze', 186),)),
    'Dance': (56, (('Dance', 178),)),
    'Ready': (56, (('Ready', 176),)),
    'Listening...': (24, (('Listening...', 133),)),
}


def _set_font(size):
    name = _DEJAVU_NAMES.get(size)
    font = getattr(M5.Lcd.FONTS, name, None) if name else None
    if font is not None:
        try:
            M5.Lcd.setFont(font)
            return
        except Exception:
            pass
    try:
        M5.Lcd.setTextSize(2)
    except Exception:
        pass


def _fallback_layout(text):
    """Single-line estimate for a label not in _LAYOUT_TABLE. No pixel
    width, so _draw_lines left-aligns it instead of centering."""
    max_width = SCREEN_W - 2 * MARGIN
    for size in _FONT_CANDIDATES:
        if len(text) * size * _CHAR_WIDTH_FACTOR <= max_width:
            return size, ((text, None),)
    return _FONT_CANDIDATES[-1], ((text, None),)


def _layout_for(text):
    return _LAYOUT_TABLE.get(text) or _fallback_layout(text)


def _draw_lines(line_widths, font_size, bg, fg):
    """line_widths: ((text, pixel_width_or_None), ...)."""
    try:
        M5.Lcd.startWrite()
    except Exception:
        pass
    try:
        M5.Lcd.fillScreen(bg)
        _set_font(font_size)
        try:
            M5.Lcd.setTextColor(fg, bg)
        except Exception:
            pass
        n = len(line_widths)
        total_h = n * font_size + (n - 1) * LINE_GAP
        y = SCREEN_H // 2 - total_h // 2
        if y < 0:
            y = 0
        for text, width in line_widths:
            x = MARGIN if width is None else max(MARGIN, (SCREEN_W - width) // 2)
            try:
                M5.Lcd.setCursor(x, y)
                M5.Lcd.print(text)
            except Exception:
                pass
            y += font_size + LINE_GAP
    finally:
        try:
            M5.Lcd.endWrite()
        except Exception:
            pass


def _draw_centered(text, bg, fg=None):
    if fg is None:
        fg = WHITE if bg != WHITE else BLACK
    font_size, line_widths = _layout_for(text)
    _draw_lines(line_widths, font_size, bg, fg)


class NarratorUI(object):
    def __init__(self):
        try:
            M5.Lcd.setRotation(ROTATION)
        except Exception as e:
            print("  setRotation err: %s" % str(e))

    def paint_booting(self):
        _draw_centered("Starting", AMBER, fg=BLACK)

    def paint_idle(self):
        _draw_centered("Listening...", BLACK)

    def paint_game(self, tag):
        color = color_for_tag(tag)
        if color is not None:
            _draw_centered(label_for_tag(tag), color, fg=BLACK)
        else:
            _draw_centered(label_for_tag(tag), BLUE)
