"""Tag -> spoken label + WAV path for the StickS3 Narrator.

Covers game start/stop and Freeze Dance's raw Go/Freeze/Dance/Ready calls.
Does not cover LED-matrix content or the Programming Station's
scanned-color broadcast -- see README.md's "Broadcast coverage" section.

WAV files are not generated by this module -- see
assets/_generate_phrases.py, then upload assets/speech/*.wav to
/flash/assets/speech/ on the device.
"""

from game_tags import GAME_TAGS

# ── WAV format required on-device ──────────────────────────────────────────
# Mono, 16-bit PCM, 16000 Hz -- what M5.Speaker.playWavFile() expects driving
# StickS3's ES8311 codec. assets/_generate_phrases.py produces exactly this.

SPEECH_DIR = "/flash/assets/speech"

# Kept in sync by hand with M5Paper Remote's config.ALL_GAMES labels
# (../M5Paper Remote/config.py). Nothing enforces this automatically.
GAME_LABELS = {
    "colorquest": "Color Quest",
    "freezedance": "Freeze Dance",
    "jumpin": "Jump In",
    "cooking": "Cooking",
    "melody": "Melody",
    "shake": "Shake Fill",
    "shakerainbow": "Shake Rainbow",
    "rainbow": "Rainbow",
    "jump": "Jump Counter",
    "sound": "Bell Choir",
    "nfcsound": "NFC Bell Choir",
    "simpleicecream": "Ice Cream",
    "multiicecream": "Multi Ice Cream",
    "gestures": "Gestures",
}

# Non-game announcements. Keys double as WAV filenames (below) and as the
# `tag` values main.py passes in for boot-ready / stop events.
SPECIAL_LABELS = {
    "ready": "Narrator ready",
    "stop": "Stopped",
}

# Freeze Dance's caller wand broadcasts these as raw (non-JSON) ESP-NOW
# byte-strings, bypassing the start_game/stop vocabulary. See
# ../Wand Module/freeze_dance.py's MSG_* constants and BROADCASTS dict.
# FD_RESET is in freeze_dance.py's receive-side vocabulary but no caller
# path sends it as of this writing; included here in case that changes.
FREEZE_DANCE_CALLS = {
    b"FD_GO": "fd_go",
    b"FD_FREEZE": "fd_freeze",
    b"FD_DANCE": "fd_dance",
    b"FD_RESET": "fd_reset",
}

FREEZE_DANCE_LABELS = {
    "fd_go": "Go",
    "fd_freeze": "Freeze",
    "fd_dance": "Dance",
    "fd_reset": "Ready",
}


# LCD text color per tag, matched to the wand's LED matrix. Hand-copied
# from ../lib/leds.py's palette (not imported -- leds.py pulls in
# NeoPixel/hubtype for the wand's hardware, not this device) and scaled up
# by the same gain factor Live_Page/wand_icons.html uses, since leds.py's
# values are dimmed for NeoPixel current draw. Keep in sync by hand if
# leds.py's palette changes.
_LED_GAIN = 255 / 140
_RED = (130, 0, 0)
_GREEN = (0, 230, 0)
_PURPLE = (50, 0, 250)
_WHITE = (140, 150, 150)
_AMBER = (120, 80, 0)
_TEAL = (0, 180, 100)
_GREEN_DIM = (0, 115, 0)


def _hex(rgb):
    r = min(255, round(rgb[0] * _LED_GAIN))
    g = min(255, round(rgb[1] * _LED_GAIN))
    b = min(255, round(rgb[2] * _LED_GAIN))
    return (r << 16) | (g << 8) | b


# Color of the LED matrix's entry icon when each game starts, from reading
# each game module. None (use the UI's neutral default) for:
#   - jumpin / shake / jump / sound / nfcsound: matrix starts off, lights
#     up on button press / shake / note.
#   - rainbow: shows a repeating multi-color pattern, not one color.
#   - gestures: entry visual is mode-dependent.
GAME_ICON_COLORS = {
    "colorquest": _hex(_GREEN_DIM),  # per wand_icons.html: "waiting between rounds"
    "freezedance": _hex(_WHITE),  # breathing white arrow, role-select
    "jumpin": None,
    "cooking": _hex(_AMBER),  # breathing amber flame, ready-to-scan
    "melody": _hex(_TEAL),  # music-note icon, ready-to-scan
    "shake": None,
    "shakerainbow": _hex(_WHITE),  # solid white fill at level 0, before any shake
    "rainbow": None,
    "jump": None,
    "sound": None,
    "nfcsound": None,
    "simpleicecream": _hex(_WHITE),  # empty cup
    "multiicecream": _hex(_WHITE),  # empty cup
    "gestures": None,
}

FREEZE_DANCE_CALL_COLORS = {
    "fd_go": _hex(_GREEN),
    "fd_freeze": _hex(_RED),
    "fd_dance": _hex(_PURPLE),
    # Caller (amber) vs. player (yellow) role isn't known here; uses the
    # white color shared by both roles' waiting states instead.
    "fd_reset": _hex(_WHITE),
}


def color_for_tag(tag):
    """0xRRGGBB for `tag`, or None for the UI's neutral default."""
    if tag in GAME_ICON_COLORS:
        return GAME_ICON_COLORS[tag]
    return FREEZE_DANCE_CALL_COLORS.get(tag)


def _wav_path(key):
    return "%s/%s.wav" % (SPEECH_DIR, key)


def tag_for_raw_bytes(data):
    """Tag for a raw (non-JSON) ESP-NOW payload, or None if not a
    recognized Freeze Dance call."""
    return FREEZE_DANCE_CALLS.get(bytes(data)) if data is not None else None


def phrase_for_tag(tag):
    """WAV path to play for `tag`, or None if there is no clip for it.

    `tag` is a game tag (e.g. "freezedance"), a special key ("ready",
    "stop"), or a Freeze Dance call tag ("fd_go", "fd_freeze", "fd_dance",
    "fd_reset").
    """
    if tag in SPECIAL_LABELS or tag in GAME_LABELS or tag in FREEZE_DANCE_LABELS:
        return _wav_path(tag)
    return None


def label_for_tag(tag):
    """Human-readable text for the LCD. Falls back to the raw tag."""
    if tag in SPECIAL_LABELS:
        return SPECIAL_LABELS[tag]
    if tag in FREEZE_DANCE_LABELS:
        return FREEZE_DANCE_LABELS[tag]
    return GAME_LABELS.get(tag, tag)


def validate_phrases():
    """Warn if a GAME_TAGS entry has no spoken label."""
    missing = [t for t in GAME_TAGS if t not in GAME_LABELS]
    if missing:
        print(
            "  [WARN] StickS3 Narrator: no spoken label for tags: %s"
            % ", ".join(sorted(missing))
        )
