"""Spoken-phrase catalog + WAV asset paths for the StickS3 Narrator.

Tier 0 scope: game start/stop, PLUS Freeze Dance's own call-and-response
broadcasts (Go/Freeze/Dance below) -- NOT individual LED-matrix content
(colors, shapes, correct/wrong flashes) and NOT the Programming Station's
scanned-color broadcast (see ../../../AGENTS.md-style audit in README.md's
"Broadcast coverage" section for why that one's still an open question).
Narrating LED-matrix content would need a narration hook inside each wand
game module -- a hardware-agnostic change touching both
`Bag2/Code/Wand Module/` and `Bag3/Code/Wand Module/`, and because Bag2
wands are already in classrooms, subject to the Bag2 verification gate in
../../../AGENTS.md. Deliberately out of scope here.

WAV files are NOT generated by this module -- see assets/_generate_phrases.py
for an offline-TTS dev helper, then upload assets/speech/*.wav to
/flash/assets/speech/ on the device.
"""

from game_tags import GAME_TAGS

# ── WAV format required on-device ──────────────────────────────────────────
# Mono, 16-bit PCM, 16000 Hz -- what M5.Speaker.playWavFile() expects driving
# StickS3's ES8311 codec. assets/_generate_phrases.py produces exactly this.

SPEECH_DIR = "/flash/assets/speech"

# Spoken label per game tag -- kept in sync BY HAND with M5Paper Remote's
# config.ALL_GAMES labels (../M5Paper Remote/config.py) so the two
# teacher-facing devices say the same names for the same games. Nothing
# enforces this automatically -- see the game-tags drift warning in
# ../../../AGENTS.md for the general pattern.
GAME_LABELS = {
    "colorquest": "Color Quest",
    "freezedance": "Freeze Dance",
    "jumpin": "Jump In",
    "cooking": "Cooking",
    "melody": "Melody",
    "shake": "Shake Fill",
    "shakerainbow": "Shake Rainbow",
    "rainbow": "Rainbow",
    "jump": "Jump Counter",
    "sound": "Bell Choir",
    "nfcsound": "NFC Bell Choir",
    "simpleicecream": "Ice Cream",
    "multiicecream": "Multi Ice Cream",
    "gestures": "Gestures",
}

# Non-game announcements. Keys double as WAV filenames (below) and as the
# `tag` values main.py passes in for boot-ready / stop events.
SPECIAL_LABELS = {
    "ready": "Narrator ready",
    "stop": "Stopped",
}

# Freeze Dance's CALLER wand broadcasts these as RAW (non-JSON) ESP-NOW
# byte-strings -- entirely bypassing the start_game/stop vocabulary -- to
# call live game state out to every other wand and to the Speaker/
# DialSpeaker units. See ../Wand Module/freeze_dance.py's MSG_* constants
# and BROADCASTS dict. Narrating these is still Tier 0: freeze_dance.py
# already sends them today, unmodified -- the Narrator just needs to
# recognize the raw bytes too, same as it recognizes the JSON start_game/
# stop messages.
#
# "FD_RESET" is in freeze_dance.py's RECEIVE-side vocabulary (its
# BROADCASTS dict has no 'reset' entry, so no caller path sends it as of
# this writing) -- included here defensively in case that changes.
FREEZE_DANCE_CALLS = {
    b"FD_GO": "fd_go",
    b"FD_FREEZE": "fd_freeze",
    b"FD_DANCE": "fd_dance",
    b"FD_RESET": "fd_reset",
}

FREEZE_DANCE_LABELS = {
    "fd_go": "Go",
    "fd_freeze": "Freeze",
    "fd_dance": "Dance",
    "fd_reset": "Ready",
}


# ── Icon colors (LCD text color, matched to the wand's LED matrix) ─────────
# Hand-copied from ../lib/leds.py's palette -- NOT imported, since leds.py
# pulls in NeoPixel/hubtype and is written for the wand's own hardware, not
# this device. Keep these values in sync by hand if leds.py's palette
# changes. Scaled up for a crisp LCD -- leds.py's values are deliberately
# dimmed for outdoor NeoPixel visibility/current draw (see its own comment
# header), which would look muddy as on-screen text -- using the same gain
# factor Live_Page/wand_icons.html applies for the same reason.
_LED_GAIN = 255 / 140
_RED = (130, 0, 0)
_GREEN = (0, 230, 0)
_PURPLE = (50, 0, 250)
_WHITE = (140, 150, 150)
_AMBER = (120, 80, 0)
_TEAL = (0, 180, 100)
_GREEN_DIM = (0, 115, 0)


def _hex(rgb):
    r = min(255, round(rgb[0] * _LED_GAIN))
    g = min(255, round(rgb[1] * _LED_GAIN))
    b = min(255, round(rgb[2] * _LED_GAIN))
    return (r << 16) | (g << 8) | b


# Per-game color, matched to the ENTRY icon the wand's LED matrix actually
# shows the moment that game starts -- verified by reading each game module
# directly, not guessed. Full audit in README.md's "Icon colors" section.
# None means "no single confident match -- use the UI's neutral default,"
# for two different real reasons:
#   - jumpin / shake / jump / sound / nfcsound: the matrix starts genuinely
#     OFF and only lights up once you press the button / shake / hold a
#     note -- there is no icon to match at the moment the game starts.
#   - rainbow: shows a repeating multi-color rainbow, not one color.
#   - gestures: its entry visual is mode-dependent; not pinned down here.
GAME_ICON_COLORS = {
    "colorquest": _hex(_GREEN_DIM),  # per wand_icons.html: "waiting between rounds"
    "freezedance": _hex(_WHITE),  # breathing white arrow, role-select
    "jumpin": None,
    "cooking": _hex(_AMBER),  # breathing amber flame, ready-to-scan
    "melody": _hex(_TEAL),  # music-note icon, ready-to-scan
    "shake": None,
    "shakerainbow": _hex(_WHITE),  # solid white fill at level 0, before any shake
    "rainbow": None,
    "jump": None,
    "sound": None,
    "nfcsound": None,
    "simpleicecream": _hex(_WHITE),  # empty cup
    "multiicecream": _hex(_WHITE),  # empty cup
    "gestures": None,
}

FREEZE_DANCE_CALL_COLORS = {
    "fd_go": _hex(_GREEN),
    "fd_freeze": _hex(_RED),
    "fd_dance": _hex(_PURPLE),
    # freeze_dance.py's actual "ready" color depends on caller (amber) vs.
    # player (yellow) role, which this device has no way to know -- using
    # the breathing-white-arrow color shared by both roles' waiting states
    # (ROLE_SELECT / REJOIN_ARMED) instead of guessing a role.
    "fd_reset": _hex(_WHITE),
}


def color_for_tag(tag):
    """0xRRGGBB to color the LCD text with for `tag`, or None for the UI's
    neutral default. SPECIAL_LABELS tags ("ready"/"stop") always return
    None -- they're not a game and have no matrix icon to match."""
    if tag in GAME_ICON_COLORS:
        return GAME_ICON_COLORS[tag]
    return FREEZE_DANCE_CALL_COLORS.get(tag)


def _wav_path(key):
    return "%s/%s.wav" % (SPEECH_DIR, key)


def tag_for_raw_bytes(data):
    """Narrator tag for a raw (non-JSON) ESP-NOW payload, or None if it's
    not one of the recognized Freeze Dance calls. Anything else received
    as msg_type=="raw" is deliberately left un-narrated rather than guessed
    at -- see FREEZE_DANCE_CALLS above."""
    return FREEZE_DANCE_CALLS.get(bytes(data)) if data is not None else None


def phrase_for_tag(tag):
    """WAV path to play for `tag`, or None if there is no clip for it.

    `tag` is a game tag (e.g. "freezedance"), a special key ("ready",
    "stop"), or a Freeze Dance call tag ("fd_go", "fd_freeze", "fd_dance",
    "fd_reset").
    """
    if tag in SPECIAL_LABELS or tag in GAME_LABELS or tag in FREEZE_DANCE_LABELS:
        return _wav_path(tag)
    return None


def label_for_tag(tag):
    """Human-readable text for the LCD. Falls back to the raw tag."""
    if tag in SPECIAL_LABELS:
        return SPECIAL_LABELS[tag]
    if tag in FREEZE_DANCE_LABELS:
        return FREEZE_DANCE_LABELS[tag]
    return GAME_LABELS.get(tag, tag)


def validate_phrases():
    """Every GAME_TAGS entry should have a spoken label -- catches drift
    with lib/game_tags.py at boot, same spirit as M5Paper's
    config.validate_config()."""
    missing = [t for t in GAME_TAGS if t not in GAME_LABELS]
    if missing:
        print(
            "  [WARN] StickS3 Narrator: no spoken label for tags: %s"
            % ", ".join(sorted(missing))
        )
